Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -1,66 +1,101 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
-
-name: CI/CD
+name: cicd
 
 on:
   push:
-    branches: [ "master" ]
-  pull_request:
     branches: [ "master" ]
 
 permissions:
   contents: read
 
-env:
-  S3_BUCKET_NAME: bemo-deploy
 jobs:
   build:
-
     runs-on: ubuntu-latest
-
     steps:
-    - uses: actions/checkout@v3
-    - name: Set up JDK 11
-      uses: actions/setup-java@v3
-      with:
-        java-version: '11'
-        distribution: 'temurin'
-    - name: Grant execute permission for gradlew
-      run: chmod +x gradlew
-    - name: Build with Gradle
-      # uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
-      # with:
-        # arguments: build
-      run : ./gradlew clean build
-    - name: Docker build
-      run : |
-        docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
-        docker build -t spring-cicd .
-        docker tag spring-cicd bemobemo/spring-cicd:${GITHUB_SHA::7}
-        docker push bemobemo/spring-cicd:${GITHUB_SHA::7}
-    # 디렉토리 생성
-    - name: Make Directory
-      run: mkdir -p deploy
 
-    # Jar 파일 복사
-    - name: Copy Jar
-      run: cp ./build/libs/*.jar ./deploy
+      - name: checkout
+      - uses: actions/checkout@v3
+      - run: touch ./src/main/resources/application.properties
+      - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties
+      - run: cat ./src/main/resources/application.properties
+      - run: touch ./src/main/resources/application.properties
+      - run: echo "${{ secrets.DBAPPLICATION }}" > ./src/main/resources/application-db.properties
+      - run: cat ./src/main/resources/application.properties
+      - run: touch ./src/main/resources/application.properties
+      - run: echo "${{ secrets.OAUTHAPPLICATION }}" > ./src/main/resources/application-oauth.properties
+      - run: cat ./src/main/resources/application.properties
+      - name: Set up JDK 11
+        uses: actions/setup-java@v3
+        with:
+          java-version: '11'
+          distribution: 'temurin'
 
-    - name: Make zip file
-      run: zip -r ./bemo.zip ./deploy
-      shell: bash
 
-    - name: Configure AWS credentials
-      uses: aws-actions/configure-aws-credentials@v1
-      with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: ap-northeast-2
 
-    - name: Upload to S3
-      run: aws s3 cp --region ap-northeast-2 ./bemo.zip s3://$S3_BUCKET_NAME/
+      ## build Docker and Push Docker Hub
+      - name: build with Gradle
+        run: ./gradlew --exclude-task test
+      - name: build Docker
+        run: |
+          docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
+          docker build -t ${{ secrets.DOCKER_REPO }} .
+          docker push ${{ secrets.DOCKER_REPO }}:latest
+      - name: Run scripts in server
+        uses: appleboy/ssh-action@master
+        with:
+          key: ${{ secrets.SSH_KEY }}
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.HOST_USERNAME }}
+          script: |
+            sudo docker pull ${{ secrets.DOCKER_REPO }}:latest
+            
+            echo "실행 중인 도커 확인.."
+            RUNNING_SERVER=$(sudo docker ps --format 'table{{.Names}}' | grep AA)
+            if [ -z "${RUNNING_SERVER}"]
+            then 
+              echo "BB 가 실행중입니다. BB -> AA 서버 교체를 진행합니다.."
+              START_CONTAINER=AA
+              TERMINATE_CONTAINER=BB
+              START_PORT=8080
+              TERMINATE_PORT=8081
+              sudo docker run -d -p 8080:8080 --name AA --log-driver=awslogs --log-opt awslogs-region=ap-northeast-2 --log-opt awslogs-group=${{ secrets.LOG_GROUP_NAME }} --log-opt awslogs-stream=${{ secrets.LOG_STREAM_NAME }} ${{ secrets.DOCKER_REPO }}
+            else
+              echo "AA가 실행중입니다. AA -> BB 서버 교체를 진행합니다.."
+              START_CONTAINER=BB
+              TERMINATE_CONTAINER=AA
+              START_PORT=8081
+              TERMINATE_PORT=8080
+              sudo docker run -d -p 8081:8080 --name BB --log-driver=awslogs --log-opt awslogs-region=ap-northeast-2 --log-opt awslogs-group=${{ secrets.LOG_GROUP_NAME }} --log-opt awslogs-stream=${{ secrets.LOG_STREAM_NAME }} ${{ secrets.DOCKER_REPO }}
+            fi
+            
+            for cnt in {1..10} 
+            do
+                echo "check server start.."
+            
+                UP=$(curl -s http://127.0.0.1:${START_PORT}/actuator/health | grep 'UP')
+                if [ -z "${UP}" ] 
+                then
+                    echo "서버가 아직 실행되지 않았습니다.."
+                else
+                    echo "서버 실행이 확인 되었습니다."
+                    break
+                fi
+            
+                echo "10초간 대기 합니다.." 
+                sleep 10
+            done
+            
+            if [ $cnt -eq 10 ] 
+            then
+              echo "deployment failed."
+              exit 1
+            fi
+            
+            echo "server start!"
+            
+            echo "change nginx server port"
+            sudo sed -i "s/${TERMINATE_PORT}/${START_PORT}/" /etc/nginx/conf.d/service-url.inc
+            sudo service nginx restart
+            
+            sudo docker stop ${TERMINATE_CONTAINER}
+            sudo docker rm ${TERMINATE_CONTAINER}
+            sudo docker image prune -f
